# Generated by Django 2.1.2 on 2018-10-28 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_perros_rescatados'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perros_rescatados',
            old_name='fotografia_perro',
            new_name='foto_perro',
        ),
    ]
